FROM node:24-alpine AS base 

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY predictive-maintenance-app/package*.json ./
RUN npm ci && npm cache clean --force

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY predictive-maintenance-app/. .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

COPY --from=builder /app/app/failure-prediction/public/test_data.csv ./app/failure-prediction/public/test_data.csv

USER nextjs

EXPOSE 8080

ENV PORT=8080

CMD ["npm", "start"]
