FROM node:24-alpine
WORKDIR /usr/src/app
COPY alerts-app/package*.json ./
RUN npm install
WORKDIR /usr/src/app/client
COPY alerts-app/client/package*.json ./
RUN npm install
COPY alerts-app/client .
RUN npm run build
WORKDIR /usr/src/app
COPY alerts-app/. .
EXPOSE 8080
ENV PORT=8080
CMD ["npm", "start"]
